# fly.toml app configuration file generated for lingam-delights on 2024-07-30T19:33:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lingam-delights'
primary_region = 'ams'

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
