import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "@/components/navigation-bar/NavigationBar";
import { Roboto } from "next/font/google";
// import { Footer } from "@/components/footer/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Dilu Dora",
  description: "Generated by create next app",
};

// this is the root, where all children (pages) are rendered
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavigationBar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
